version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    volumes:
    - /srv/docker/redmine/postgresql:/var/lib/postgresql
    networks:
    - default
    environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
    restart: always

  redmine:
    image: sameersbn/redmine:3.4.4-2
    container_name: redmine
    depends_on:
    - postgresql
    volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
    networks:
    - default
    - common_link
    restart: always
    environment:
    - TZ=Asia/Kolkata

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production

    - REDMINE_RELATIVE_URL_ROOT=/redmine

networks:
  common_link:
    external: true
